name: Flutter CI

# Define quando a ação vai rodar
on:
  push:
    branches: [ "main" ] # Altere para "master" se for o caso
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run Linter
        run: flutter analyze

      - name: Run Tests
        run: flutter test